-- =====================================================================
-- 시드 데이터 (개발/시연용)
-- 계정 / 비밀번호 :
--   admin  : admin1234!    (시스템 관리자, ACTIVE)
--   jypark : manager1234!  (영업관리부 매니저, ACTIVE)
--   jhlee  : emp1234!      (물류관리부 사원, ACTIVE)
--   sachoi : emp1234!      (영업관리부 사원, PENDING — 승인 대기 데모용)
--   su123  : emp1234!      (인사부 사원, PENDING - 승인 거절 데모용)
--   mkjung : emp1234!      (경영지원부 사원, REJECTED — 거절 데모용)
-- =====================================================================

-- 1. 부서
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_CODE, DEPT_NAME, DESCRIPTION, USE_YN, CREATED_AT)
VALUES (SEQ_DEP_ID.NEXTVAL, 'DEPT_SAL', '영업관리부',
        '약국/병원 거래처 주문 접수 및 수금 관리', 'Y', TO_DATE('2024-01-02','YYYY-MM-DD'));

INSERT INTO DEPARTMENT (DEPT_ID, DEPT_CODE, DEPT_NAME, DESCRIPTION, USE_YN, CREATED_AT)
VALUES (SEQ_DEP_ID.NEXTVAL, 'DEPT_LOG', '물류관리부',
        '의약품 발주, 입고, 재고, 출고 관리', 'Y', TO_DATE('2024-01-02','YYYY-MM-DD'));

INSERT INTO DEPARTMENT (DEPT_ID, DEPT_CODE, DEPT_NAME, DESCRIPTION, USE_YN, CREATED_AT)
VALUES (SEQ_DEP_ID.NEXTVAL, 'DEPT_FIN', '경영지원부',
        '정산, 여신 한도 관리, 손익 분석', 'Y', TO_DATE('2024-01-02','YYYY-MM-DD'));

INSERT INTO DEPARTMENT (DEPT_ID, DEPT_CODE, DEPT_NAME, DESCRIPTION, USE_YN, CREATED_AT)
VALUES (SEQ_DEP_ID.NEXTVAL, 'DEPT_HR', '인사부',
        '직원 계정 발급, 인사 정보 및 근태 관리', 'Y', TO_DATE('2024-01-02','YYYY-MM-DD'));

-- 2. 사원
-- 시스템 관리자 (경영지원부)
INSERT INTO EMPLOYEE (EMP_ID, LOGIN_ID, PASSWORD, EMP_NAME, PHONE, EMAIL, DEPT_ID, ROLE_CODE, STATUS, HIRE_DATE, CREATED_AT)
VALUES (EMP_SEQ.NEXTVAL, 'admin',
        '$2a$10$kxPFE1ZkuRiVNbfzGIpPmuMfx1pX6Qah74uSujJbBCLA2PnLC0yYC',
        '김성훈', '010-3825-1147', 'shkim@hanbitpharm.co.kr',
        (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DEPT_FIN'),
        'ADMIN', 'ACTIVE', TO_DATE('2021-03-02','YYYY-MM-DD'), SYSDATE);

-- 영업관리부 매니저
INSERT INTO EMPLOYEE (EMP_ID, LOGIN_ID, PASSWORD, EMP_NAME, PHONE, EMAIL, DEPT_ID, ROLE_CODE, STATUS, HIRE_DATE, CREATED_AT)
VALUES (EMP_SEQ.NEXTVAL, 'jypark',
        '$2a$10$xonNmp7/DoD.MOCHCXbtOuNU74ZiuObNLLjVos6joKdmkvm89.QA.',
        '박지연', '010-7264-3391', 'jypark@hanbitpharm.co.kr',
        (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DEPT_SAL'),
        'MANAGER', 'ACTIVE', TO_DATE('2022-07-01','YYYY-MM-DD'), SYSDATE);

-- 물류관리부 사원 (승인 완료)
INSERT INTO EMPLOYEE (EMP_ID, LOGIN_ID, PASSWORD, EMP_NAME, PHONE, EMAIL, DEPT_ID, ROLE_CODE, STATUS, HIRE_DATE, CREATED_AT)
VALUES (EMP_SEQ.NEXTVAL, 'jhlee',
        '$2a$10$ZQD5z3RVMKuV/xS6j9Q/T.ZM751lDYSug2oIXQfxOYR7aRjcHqhHi',
        '이준호', '010-5118-9027', 'jhlee@hanbitpharm.co.kr',
        (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DEPT_LOG'),
        'STAFF', 'ACTIVE', TO_DATE('2023-11-13','YYYY-MM-DD'), SYSDATE);

-- 영업관리부 신규 입사자 (승인 대기/승인 확인 — 관리자 승인 화면 데모용)
INSERT INTO EMPLOYEE (EMP_ID, LOGIN_ID, PASSWORD, EMP_NAME, PHONE, EMAIL, DEPT_ID, ROLE_CODE, STATUS, CREATED_AT)
VALUES (EMP_SEQ.NEXTVAL, 'sachoi',
        '$2a$10$ZQD5z3RVMKuV/xS6j9Q/T.ZM751lDYSug2oIXQfxOYR7aRjcHqhHi',
        '최수아', '010-9043-6172', 'sachoi@hanbitpharm.co.kr',
        (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DEPT_SAL'),
        'STAFF', 'PENDING', SYSDATE);

-- 인사부 신규 입사자 (승인 대기/거절 확인 — 관리자 승인 화면 데모용)
INSERT INTO EMPLOYEE (EMP_ID, LOGIN_ID, PASSWORD, EMP_NAME, PHONE, EMAIL, DEPT_ID, ROLE_CODE, STATUS, CREATED_AT)
VALUES (EMP_SEQ.NEXTVAL, 'sachoi',
        '$2a$10$ZQD5z3RVMKuV/xS6j9Q/T.ZM751lDYSug2oIXQfxOYR7aRjcHqhHi',
        '도수환', '010-6648-2215', 'su123@hanbitpharm.co.kr',
        (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DEPT_HR'),
        'STAFF', 'PENDING', SYSDATE);

-- 가입 거절 사례 (거절 메시지 데모용)
INSERT INTO EMPLOYEE (EMP_ID, LOGIN_ID, PASSWORD, EMP_NAME, PHONE, EMAIL, DEPT_ID, ROLE_CODE, STATUS, CREATED_AT)
VALUES (EMP_SEQ.NEXTVAL, 'mkjung',
        '$2a$10$ZQD5z3RVMKuV/xS6j9Q/T.ZM751lDYSug2oIXQfxOYR7aRjcHqhHi',
        '정민규', '010-2271-8845', 'mkjung@hanbitpharm.co.kr',
        (SELECT DEPT_ID FROM DEPARTMENT WHERE DEPT_CODE = 'DEPT_FIN'),
        'STAFF', 'REJECTED', SYSDATE);

-- 3. 부서 × 역할 예외 권한 (물류관리부 사원 = 관리약사 → 재고 조정 권한)
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_LOG', 'ROLE_STAFF', '관리약사', 'EX_LOG_STOCK_ADJUST',
        '물류관리부 사원 중 관리약사에게 재고 조정 권한 부여');

-- 물류부서 (DEPT_LOG)
-- [매니저] 재고 조정 권한
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_LOG', 'ROLE_MANAGER', '재고 조정관', 'EX_LOG_STOCK_ADJUST', '물류부 매니저 중 실물 재고 오차 수정 및 조정 권한');

-- [직원] 관리약사 권한 (의약품/위험물 취급 부서 특수 직함)
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_LOG', 'ROLE_STAFF', '관리약사', 'EX_LOG_MED_MANAGE', '물류부 직원 중 전문 의약품 반출 승인 권한');

-- 재무/회계부서 (DEPT_FIN)
-- [매니저] 자금 집행 고액 승인 권한
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_FIN', 'ROLE_MANAGER', '고액 결재권자', 'EX_FIN_HIGH_AMOUNT', '재무부 매니저 중 5천만 원 이상 지출 승인 권한');

-- [직원] 감사 보조 권한 (시즌 한정 또는 특정 직원 부여)
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_FIN', 'ROLE_STAFF', '내부 감사원', 'EX_FIN_AUDIT_ASSIST', '재무부 직원 중 회계 장부 마감 검증 및 감사 로그 열람 권한');

-- 인사/총무부서 (DEPT_HR)
-- [매니저] 채용/평가 정보 열람 권한
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_HR', 'ROLE_MANAGER', '인사평가 위원', 'EX_HR_EVAL_VIEW', '인사부 매니저 중 임직원 고과 성과 지표 열람 및 수정 권한');

-- [직원] 개인정보 마스킹 해제 권한
INSERT INTO DEPT_ROLE_EXCEPTION (EXCEPTION_ID, DEPT_CODE, ROLE_CODE, EXCEPTION_TITLE, EXCEPTION_AUTH, DESCRIPTION)
VALUES (SEQ_DEPT_ROLE_EXCEPTION.NEXTVAL, 'DEPT_HR', 'ROLE_STAFF', '개인정보 취급자', 'EX_HR_PRIVACY_UNMASK', '인사부 직원 중 증명서 발급 등을 위한 주민번호 마스킹 해제 권한');

COMMIT;
