ALTER TABLE RETURN_REQUEST
    ADD SHIPMENT_DETAIL_ID NUMBER(10);

ALTER TABLE RETURN_REQUEST
    ADD CONSTRAINT FK_RET_REQ_SHIP_DETAIL
        FOREIGN KEY (SHIPMENT_DETAIL_ID)
            REFERENCES SHIPMENT_DETAIL(SHIPMENT_DETAIL_ID);

ALTER TABLE RETURN_REQUEST ADD APPROVED_BY NUMBER(10);
ALTER TABLE RETURN_REQUEST ADD APPROVED_AT TIMESTAMP(6);
ALTER TABLE RETURN_REQUEST ADD COMPLETED_AT TIMESTAMP(6);
ALTER TABLE RETURN_REQUEST ADD REJECT_REASON VARCHAR2(500);

ALTER TABLE RETURN_REQUEST
    ADD CONSTRAINT FK_RET_REQ_APPROVED_BY
        FOREIGN KEY (APPROVED_BY)
            REFERENCES EMPLOYEE(EMP_ID);

ALTER TABLE RETURN_REQUEST
    MODIFY CREATED_AT DEFAULT SYSTIMESTAMP NOT NULL;

ALTER TABLE RETURN_REQUEST
    ADD RETURN_GROUP_ID NUMBER(10) default 0 NOT NULL;

CREATE SEQUENCE SEQ_RETURN_REQUEST_GROUP_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE