spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: 여기에_DB계정입력        # 예: dydrl
    password: 여기에_DB비밀번호입력    # 예: dydrl1234
    driver-class-name: oracle.jdbc.OracleDriver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.erp
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

logging:
  level:
    com.erp: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs